### ISSUE TITLE
psql password?

### ISSUE THREAD

**Issue by axd1967** [GeograpHack/afg#7]
probeerde server in gang te trekken, maar het lukt niet, ik krijg foutmeldingen, zie https://github.com/GeograpHack/afg/blob/33eaf8d2974fba0c4a73141534f8b87d99b6527a/postmortem.md, kan het zijn dat de DB apart moet opgezet worden?

**Comment by mivdnber** [comment]
De vagrant machine doet niets. Ik heb die voor de start van de hackathon in het projectsjabloon gezet om snel een PostGIS database te kunnen opzetten.

De database is inderdaad niet geïnitialiseerd; korte -hoogstwaarschijnlijk onvolledige- instructies (uitgevoerd als user postgres in psql):

```
create user afg password 'afg';
create database afg owner afg;
\c afg
create extension postgis;
```

Shell in project root:

```
shp2pgsql -s 4326 selectie_oneway_after.shp roads | psql -h localhost -U afg -d afg
```
